Repository onnx/onnx-mlir, pull requests merged in 2021-12, with the labels that each got.

#1026 import seq
  src/Builder/FrontendDialectTransformer.cpp
Labels: Ready for Review

#1019 Category mapper lower to llvm part2
  src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
  test/mlir/krnl/krnl_C_library_function_lowering.mlir
  test/mlir/krnl/krnl_category_mapper.mlir
  test/mlir/onnx/onnx_lowering_category_mapper.mlir
Labels: Ready for Review

#1021 Generate datalayout in module.
  MLIR.cmake
  src/Compiler/CMakeLists.txt
  src/Compiler/CompilerUtils.cpp
  src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
  test/mlir/module_op_be/module_op.mlir
  test/mlir/module_op_le/module_op.mlir
  test/mlir/onnx/onnx_location.mlir
Labels: Ready for Review

#1017 Use cmake ExternalProject to download or build jsoniter
  CMakeLists.txt
  docs/Testing.md
  src/Runtime/jni/CMakeLists.txt
  src/Runtime/jni/Jsoniter.cmake
  src/Runtime/jni/jniwrapper.c
Labels: Ready for Review

#1034 Add optional wdir to exec()
  src/Compiler/CompilerUtils.cpp
Labels: bug fix, Ready for Review

#1000 Added MemRefsNormalizable trants to krnl ops whose input or output has memref type
  src/Dialect/Krnl/KrnlOps.td
Labels: Ready for Review

#1032 Added an end to end example (Mnist)
  README.md
  docs/mnist_example/README.md
  docs/mnist_example/gen_mnist_onnx.py
  docs/mnist_example/mnist-simple.png
  docs/mnist_example/mnist.cpp
  docs/mnist_example/requirements.txt
  docs/mnist_example/update_env.sh
Labels: Ready for Review

#1039 PyRuntime shared lib protobuf error fix
  src/Compiler/CMakeLists.txt
  src/Runtime/CMakeLists.txt
  src/Runtime/PyExecutionSession.cpp
Labels: Ready for Review

#1033 Support shape inference for sequence ops
  src/Dialect/ONNX/ONNXOps.cpp
  src/Dialect/ONNX/ONNXOps.td.inc
  src/Transform/ONNX/Decompose.cpp
  src/Transform/ONNX/Decompose.td
  test/mlir/onnx/onnx_decompose.mlir
  test/mlir/onnx/onnx_shape_inference.mlir
  utils/gen_onnx_mlir.py
Labels: Ready for Review

#1046 Build fix for mac
  src/Runtime/CMakeLists.txt
Labels: bug fix

#1028 Set krnl.global alignment using module datalayout if present
  src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
  test/mlir/krnl/krnl_category_mapper.mlir
  test/mlir/krnl/krnl_global_with_alignment_lowering.mlir
Labels: Ready for Review

#1048 Fix compiler warnings
  src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
  src/Dialect/ONNX/MLIRDialectBuilder.cpp
  src/Transform/ONNX/ONNXOpTransformPass.cpp
Labels: Ready for Review

#1055 Instrumentation into blocks
  src/Transform/ONNX/InstrumentONNXPass.cpp
Labels: Ready for Review

#1062 Run MLIR BufferDeallocationPass after lowering the affine dialect.
  src/Compiler/CompilerUtils.cpp
  src/Support/OMOptions.cpp
  src/Support/OMOptions.hpp
  src/Transform/ONNX/ONNXOpTransformPass.cpp
Labels: bug fix

#1054 Fix Warnings
  src/Dialect/ONNX/IndexExprDetail.cpp
  src/Runtime/OMInstrument.inc
  src/Transform/ONNX/ONNXOpTransformPass.cpp
Labels: Ready for Review
