Repository onnx/onnx-mlir, pull requests merged in 2022-01, with the labels that each got.

#1066 Document Mac OSX workaround for check-onnx-backend.
  README.md
Labels: documentation

#1098 fix shape inference for SequenceInsert
  src/Dialect/ONNX/ONNXOps.cpp
Labels: Ready for Review

#1077 Update document
  docs/DocumentList.md
  docs/HowToAddAnOperation.md
  docs/ImportONNXDefs.md
  docs/Testing.md
  utils/gen_onnx_mlir.py
Labels: documentation, Ready for Review

#1095 Update LLVM level
  docs/BuildOnLinuxOSX.md
  docs/BuildOnWindows.md
  src/Builder/FrontendDialectTransformer.cpp
  src/Compiler/CompilerUtils.cpp
  src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
  src/Conversion/ONNXToKrnl/ControlFlow/Loop.cpp
  src/Conversion/ONNXToKrnl/ControlFlow/Scan.cpp
  src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
  src/Conversion/ONNXToKrnl/ML/CategoryMapper.cpp
  src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
  src/Conversion/ONNXToKrnl/Math/Gemm.cpp
  src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
  src/Conversion/ONNXToKrnl/ObjectDetection/NonMaxSuppression.cpp
  src/Conversion/ONNXToKrnl/Tensor/DepthToSpace.cpp
  src/Conversion/ONNXToKrnl/Tensor/Identity.cpp
  src/Conversion/ONNXToKrnl/Tensor/SpaceToDepth.cpp
  src/Dialect/Krnl/KrnlOps.cpp
  src/Dialect/ONNX/IndexExpr.cpp
  src/Dialect/ONNX/IndexExprDetail.cpp
  src/Dialect/ONNX/MLIRDialectBuilder.cpp
  src/Dialect/ONNX/ONNXOps.cpp
  test/mlir/krnl/krnl_category_mapper.mlir
  test/mlir/onnx/onnx_bundle_memory_pool.mlir
  test/mlir/onnx/onnx_lowering.mlir
  test/mlir/onnx/onnx_lowering_gru_op.mlir
  test/mlir/onnx/onnx_lowering_lstm_op.mlir
  test/mlir/onnx/onnx_lowering_nonmaxsuppression_op.mlir
  test/mlir/onnx/onnx_lowering_rnn_op.mlir
  test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
  utils/clone-mlir.sh
Labels: Ready for Review

#1102 Pass type converter to all ONNX operations
  src/Conversion/ONNXToKrnl/ControlFlow/Loop.cpp
  src/Conversion/ONNXToKrnl/ControlFlow/Scan.cpp
  src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
  src/Conversion/ONNXToKrnl/ML/CategoryMapper.cpp
  src/Conversion/ONNXToKrnl/Math/Clip.cpp
  src/Conversion/ONNXToKrnl/Math/CumSum.cpp
  src/Conversion/ONNXToKrnl/Math/Gemm.cpp
  src/Conversion/ONNXToKrnl/Math/Hardmax.cpp
  src/Conversion/ONNXToKrnl/Math/LRN.cpp
  src/Conversion/ONNXToKrnl/Math/MatMul.cpp
  src/Conversion/ONNXToKrnl/Math/RandomNormal.cpp
  src/Conversion/ONNXToKrnl/Math/Reduction.cpp
  src/Conversion/ONNXToKrnl/Math/Softmax.cpp
  src/Conversion/ONNXToKrnl/Math/TopK.cpp
  src/Conversion/ONNXToKrnl/NN/Conv.cpp
  src/Conversion/ONNXToKrnl/NN/Normalization.cpp
  src/Conversion/ONNXToKrnl/NN/Pooling.cpp
  src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
  src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
  src/Conversion/ONNXToKrnl/ObjectDetection/NonMaxSuppression.cpp
  src/Conversion/ONNXToKrnl/RNN/GRU.cpp
  src/Conversion/ONNXToKrnl/RNN/LSTM.cpp
  src/Conversion/ONNXToKrnl/RNN/RNN.cpp
  src/Conversion/ONNXToKrnl/RNN/RNNBase.hpp
  src/Conversion/ONNXToKrnl/Tensor/ArgMax.cpp
  src/Conversion/ONNXToKrnl/Tensor/Compress.cpp
  src/Conversion/ONNXToKrnl/Tensor/Concat.cpp
  src/Conversion/ONNXToKrnl/Tensor/Constant.cpp
  src/Conversion/ONNXToKrnl/Tensor/ConstantOfShape.cpp
  src/Conversion/ONNXToKrnl/Tensor/DepthToSpace.cpp
  src/Conversion/ONNXToKrnl/Tensor/Expand.cpp
  src/Conversion/ONNXToKrnl/Tensor/Flatten.cpp
  src/Conversion/ONNXToKrnl/Tensor/Gather.cpp
  src/Conversion/ONNXToKrnl/Tensor/NonZero.cpp
  src/Conversion/ONNXToKrnl/Tensor/OneHot.cpp
  src/Conversion/ONNXToKrnl/Tensor/Pad.cpp
  src/Conversion/ONNXToKrnl/Tensor/Range.cpp
  src/Conversion/ONNXToKrnl/Tensor/Reshape.cpp
  src/Conversion/ONNXToKrnl/Tensor/Resize.cpp
  src/Conversion/ONNXToKrnl/Tensor/ReverseSequence.cpp
  src/Conversion/ONNXToKrnl/Tensor/Shape.cpp
  src/Conversion/ONNXToKrnl/Tensor/Size.cpp
  src/Conversion/ONNXToKrnl/Tensor/Slice.cpp
  src/Conversion/ONNXToKrnl/Tensor/SpaceToDepth.cpp
  src/Conversion/ONNXToKrnl/Tensor/Split.cpp
  src/Conversion/ONNXToKrnl/Tensor/Squeeze.cpp
  src/Conversion/ONNXToKrnl/Tensor/Tile.cpp
  src/Conversion/ONNXToKrnl/Tensor/Transpose.cpp
  src/Conversion/ONNXToKrnl/Tensor/Unsqueeze.cpp
  src/Dialect/ONNX/MLIRDialectBuilder.cpp
Labels: Ready for Review

#1103 Nuke KrnlDummyCastOp now that we use MLIR's UnrealizedConversionCastOp
  docs/Dialects/krnl.md
  docs/Dialects/onnx.md
  src/Dialect/Krnl/CMakeLists.txt
  src/Dialect/Krnl/KrnlOps.cpp
  src/Dialect/Krnl/KrnlOps.td
  src/Dialect/Krnl/SimplifyKrnl.cpp
  src/Dialect/ONNX/ONNXOps.td.inc.dc
Labels: Ready for Review

#1116 Update LLVM to commit 676bfb2a226.
  docs/BuildOnLinuxOSX.md
  docs/BuildOnWindows.md
  src/Builder/OpBuildTable.inc.dc
  src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
  src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
  src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
  src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
  src/Dialect/Krnl/KrnlOps.cpp
  test/mlir/krnl/krnl_to_llvm_omtensor_ownership.mlir
  utils/clone-mlir.sh
Labels: build issue

#1064 Enables tiling and unrolling only at O3
  src/Compiler/CompilerUtils.cpp
  src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
  src/Conversion/ONNXToKrnl/Math/Gemm.cpp
  src/Conversion/ONNXToKrnl/Math/MatMul.cpp
  src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
  src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
  src/InitOMPasses.hpp
  src/Pass/Passes.hpp
  src/Tool/ONNXMLIROpt/ONNXMLIROpt.cpp
  src/main.cpp
  test/backend/conftest.py
  test/backend/test.py
  test/mlir/conversion/krnl_to_affine/buffer_copy.mlir
  test/mlir/conversion/krnl_to_affine/krnl_to_affine.mlir
  test/mlir/conversion/krnl_to_affine/krnl_to_affine_with_canonicalize.mlir
  test/mlir/conversion/krnl_to_affine/matmul.mlir
  test/mlir/krnl/block.mlir
  test/mlir/krnl/get_induction_var_value.mlir
  test/mlir/krnl/hoisting.mlir
  test/mlir/krnl/imperfectly_nested_stmts.mlir
  test/mlir/krnl/krnl_C_library_function_lowering.mlir
  test/mlir/krnl/krnl_bundle_aligned_memory_pool.mlir
  test/mlir/krnl/krnl_bundle_memory_pool.mlir
  test/mlir/krnl/krnl_category_mapper.mlir
  test/mlir/krnl/krnl_disconnect_dim_from_alloc.mlir
  test/mlir/krnl/krnl_enable_memory_pool.mlir
  test/mlir/krnl/krnl_getref_lowering.mlir
  test/mlir/krnl/krnl_global_with_alignment_lowering.mlir
  test/mlir/krnl/krnl_math_function_lowering.mlir
  test/mlir/krnl/krnl_normalization.mlir
  test/mlir/krnl/krnl_optimize_aligned_memory_pool.mlir
  test/mlir/krnl/krnl_optimize_memory_pool.mlir
  test/mlir/krnl/krnl_optimize_memory_pool_with_ops.mlir
  test/mlir/krnl/krnl_random_normal_lowering.mlir
  test/mlir/krnl/krnl_shape_lowering.mlir
  test/mlir/krnl/krnl_substitution.mlir
  test/mlir/krnl/krnl_to_llvm_omtensor_ownership.mlir
  test/mlir/krnl/permute.mlir
  test/mlir/krnl/reshape.mlir
  test/mlir/krnl/unroll.mlir
  test/mlir/onnx/onnx_bundle_memory_pool.mlir
  test/mlir/onnx/onnx_lowering.mlir
  test/mlir/onnx/onnx_lowering_category_mapper.mlir
  test/mlir/onnx/onnx_lowering_depth_to_space_op.mlir
  test/mlir/onnx/onnx_lowering_gru_op.mlir
  test/mlir/onnx/onnx_lowering_lstm_op.mlir
  test/mlir/onnx/onnx_lowering_nonmaxsuppression_op.mlir
  test/mlir/onnx/onnx_lowering_range_op.mlir
  test/mlir/onnx/onnx_lowering_rnn_op.mlir
  test/mlir/onnx/onnx_lowering_space_to_depth.mlir
  test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
  test/mlir/onnx/onnx_lowering_with_canonicalize_noopt.mlir
  test/mlir/onnx/onnx_math_functions_lowering.mlir
  utils/mlir2FileCheck.py
Labels: Ready for Review
